app:
  config:
    keycloak:
      url: http://localhost:8180
      realm: spickandspan
      client-secret: d5qlvDe5qQ7GIUsuEBHnFTeQQz7v08Xq
      client-id: spickandspan-client
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            user-info-authentication-method: header
        registration:
          spickandspan-client:
            provider: keycloak
            client-id: ${app.config.keycloak.client-id}
            client-secret: ${app.config.keycloak.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/products/**
        - id: tax-service
          uri: lb://tax-service
          predicates:
            - Path=/tax/**
  application:
    name: api-gateway
server:
  port: 8080
